# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/monster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/monster.proto',
  package='dadguide',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14protos/monster.proto\x12\x08\x64\x61\x64guide\"@\n\x0e\x43rossServerInt\x12\x0e\n\x02jp\x18\x01 \x01(\x05R\x02jp\x12\x0e\n\x02na\x18\x02 \x01(\x05R\x02na\x12\x0e\n\x02kr\x18\x03 \x01(\x05R\x02kr\"C\n\x11\x43rossServerString\x12\x0e\n\x02jp\x18\x01 \x01(\tR\x02jp\x12\x0e\n\x02na\x18\x02 \x01(\tR\x02na\x12\x0e\n\x02kr\x18\x03 \x01(\tR\x02kr\"\x8f\x03\n\x07Monster\x12\x1b\n\tunique_id\x18\x01 \x01(\x05R\x08uniqueId\x12\x37\n\nmonster_id\x18\x02 \x01(\x0b\x32\x18.dadguide.CrossServerIntR\tmonsterId\x12/\n\x04name\x18\x03 \x01(\x0b\x32\x1b.dadguide.CrossServerStringR\x04name\x12,\n\x06type_1\x18\x04 \x01(\x0e\x32\x15.dadguide.MonsterTypeR\x05type1\x12,\n\x06type_2\x18\x05 \x01(\x0e\x32\x15.dadguide.MonsterTypeR\x05type2\x12,\n\x06type_3\x18\x06 \x01(\x0e\x32\x15.dadguide.MonsterTypeR\x05type3\x12\x33\n\nawakenings\x18\x07 \x03(\x0e\x32\x13.dadguide.AwakeningR\nawakenings\x12>\n\x10super_awakenings\x18\x08 \x03(\x0e\x32\x13.dadguide.AwakeningR\x0fsuperAwakenings*:\n\x0bMonsterType\x12\x18\n\x14UNKNOWN_MONSTER_TYPE\x10\x00\x12\x07\n\x03GOD\x10\x01\x12\x08\n\x04WORK\x10\x02*0\n\tAwakening\x12\x15\n\x11UNKNOWN_AWAKENING\x10\x00\x12\x0c\n\x08HP_BOOST\x10\x01\x62\x06proto3')
)

_MONSTERTYPE = _descriptor.EnumDescriptor(
  name='MonsterType',
  full_name='dadguide.MonsterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_MONSTER_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORK', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=571,
  serialized_end=629,
)
_sym_db.RegisterEnumDescriptor(_MONSTERTYPE)

MonsterType = enum_type_wrapper.EnumTypeWrapper(_MONSTERTYPE)
_AWAKENING = _descriptor.EnumDescriptor(
  name='Awakening',
  full_name='dadguide.Awakening',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_AWAKENING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HP_BOOST', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=631,
  serialized_end=679,
)
_sym_db.RegisterEnumDescriptor(_AWAKENING)

Awakening = enum_type_wrapper.EnumTypeWrapper(_AWAKENING)
UNKNOWN_MONSTER_TYPE = 0
GOD = 1
WORK = 2
UNKNOWN_AWAKENING = 0
HP_BOOST = 1



_CROSSSERVERINT = _descriptor.Descriptor(
  name='CrossServerInt',
  full_name='dadguide.CrossServerInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jp', full_name='dadguide.CrossServerInt.jp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='jp', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='na', full_name='dadguide.CrossServerInt.na', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='na', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kr', full_name='dadguide.CrossServerInt.kr', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='kr', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=98,
)


_CROSSSERVERSTRING = _descriptor.Descriptor(
  name='CrossServerString',
  full_name='dadguide.CrossServerString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jp', full_name='dadguide.CrossServerString.jp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='jp', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='na', full_name='dadguide.CrossServerString.na', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='na', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kr', full_name='dadguide.CrossServerString.kr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='kr', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=167,
)


_MONSTER = _descriptor.Descriptor(
  name='Monster',
  full_name='dadguide.Monster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='dadguide.Monster.unique_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='uniqueId', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='monster_id', full_name='dadguide.Monster.monster_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='monsterId', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='dadguide.Monster.name', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_1', full_name='dadguide.Monster.type_1', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='type1', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_2', full_name='dadguide.Monster.type_2', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='type2', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type_3', full_name='dadguide.Monster.type_3', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='type3', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='awakenings', full_name='dadguide.Monster.awakenings', index=6,
      number=7, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='awakenings', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='super_awakenings', full_name='dadguide.Monster.super_awakenings', index=7,
      number=8, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='superAwakenings', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=569,
)

_MONSTER.fields_by_name['monster_id'].message_type = _CROSSSERVERINT
_MONSTER.fields_by_name['name'].message_type = _CROSSSERVERSTRING
_MONSTER.fields_by_name['type_1'].enum_type = _MONSTERTYPE
_MONSTER.fields_by_name['type_2'].enum_type = _MONSTERTYPE
_MONSTER.fields_by_name['type_3'].enum_type = _MONSTERTYPE
_MONSTER.fields_by_name['awakenings'].enum_type = _AWAKENING
_MONSTER.fields_by_name['super_awakenings'].enum_type = _AWAKENING
DESCRIPTOR.message_types_by_name['CrossServerInt'] = _CROSSSERVERINT
DESCRIPTOR.message_types_by_name['CrossServerString'] = _CROSSSERVERSTRING
DESCRIPTOR.message_types_by_name['Monster'] = _MONSTER
DESCRIPTOR.enum_types_by_name['MonsterType'] = _MONSTERTYPE
DESCRIPTOR.enum_types_by_name['Awakening'] = _AWAKENING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrossServerInt = _reflection.GeneratedProtocolMessageType('CrossServerInt', (_message.Message,), dict(
  DESCRIPTOR = _CROSSSERVERINT,
  __module__ = 'protos.monster_pb2'
  # @@protoc_insertion_point(class_scope:dadguide.CrossServerInt)
  ))
_sym_db.RegisterMessage(CrossServerInt)

CrossServerString = _reflection.GeneratedProtocolMessageType('CrossServerString', (_message.Message,), dict(
  DESCRIPTOR = _CROSSSERVERSTRING,
  __module__ = 'protos.monster_pb2'
  # @@protoc_insertion_point(class_scope:dadguide.CrossServerString)
  ))
_sym_db.RegisterMessage(CrossServerString)

Monster = _reflection.GeneratedProtocolMessageType('Monster', (_message.Message,), dict(
  DESCRIPTOR = _MONSTER,
  __module__ = 'protos.monster_pb2'
  # @@protoc_insertion_point(class_scope:dadguide.Monster)
  ))
_sym_db.RegisterMessage(Monster)


# @@protoc_insertion_point(module_scope)
